import {StyleSheet} from 'react-native';
export default EventFormStyle = StyleSheet.create({
  container: {
    flex: 1,
    // backgroundColor: '#EBEDEF',
    backgroundColor: '#E5E4E2',
  },
  heading: {
    color: '#074365',
    fontSize: 22,
    fontWeight: 'bold',
    justifyContent: 'center',
    textAlign: 'center',
    // backgroundColor:'white',
    marginHorizontal: 10,
    padding: 10,
    borderRadius: 10,
  },

  header: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 50,
  },
  footer: {
    flex: 3,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginTop: 20,
  },
  text_header: {
    textAlign: 'left',
    // color: '#fff',
    color: '#074365',
    fontWeight: 'bold',
    fontSize: 30,
    paddingBottom: 10,
  },
  text_footer: {
    color: '#05375a',
    fontSize: 15,
    paddingVertical: -70,
    marginTop: 5,
  },
  textinput: {
    flex: 1,
    paddingLeft: 10,
    // color: '#074365',
    marginTop: -1,
    color: '#074365',
    backgroundColor: '#ffffff',
    borderRadius: 10,
  },
  action: {
    flexDirection: 'row',
    marginTop: 0,
    // borderWidth: 1,
    // borderColor: '#074365',
    borderRadius: 10,
  },
  button: {
    alignItems: 'center',
    marginTop: 20,
    alignItems: 'center',
    // backgroundColor: '#009387',
    backgroundColor: '#074365',
    padding: 10,
    borderRadius: 10,
    // width:150
  },
  btnreset: {
    alignItems: 'center',
    marginTop: 20,
    alignItems: 'center',
    padding: 10,
    borderWidth: 2,
    borderColor: '#074365',
    borderRadius: 10,
    // width:150,
  },
  signIn: {
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textSubmit: {
    fontSize: 15,
    width: 70,
    color: 'white',
    textAlign: 'center',
  },
  textreset: {
    fontSize: 15,
    width: 70,
    color: '#074365',
    textAlign: 'center',
    // alignItems:'center',
    marginTop: -4,
  },
  submitbtn: {
    height: 60,

    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  option: {
    flexDirection: 'row',
    height: 50,
    // marginVertical: 5,
    color: 'red',
    // borderWidth: 1,
    //  borderBottomWidth: 1,
    borderColor: 'white',
    backgroundColor: 'white',
  },
  facilidata: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  arrowback: {
    color: '#074365',
    marginHorizontal: '100',
    padding: 10,
  },
});
